# Generated by Django 6.0.4 on 2026-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
