# Generated by Django 6.0.4 on 2026-05-15 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_businesspartneraddress'),
        ('purchasing', '0001_initial'),
        ('sales', '0003_salesorder_customer_po_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('received', 'Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='requested', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('fx_rate_date', models.DateField(blank=True, null=True)),
                ('price_gbp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier_sku', models.CharField(blank=True, max_length=100)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('so_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='sales.salesorderline')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='partners.businesspartner')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('so_line', 'supplier')},
            },
        ),
    ]
