# Generated by Django 6.0.4 on 2026-05-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_businesspartneraddress'),
        ('purchasing', '0002_supplierquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('fx_rate_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('matched', 'Matched'), ('disputed', 'Disputed'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchasing.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='partners.supplier')),
            ],
            options={
                'ordering': ['-invoice_date'],
                'unique_together': {('supplier', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('price_variance', 'Price Variance'), ('qty_variance', 'Qty Variance'), ('no_grn', 'No GRN'), ('disputed', 'Disputed')], default='unmatched', max_length=20)),
                ('match_notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.invoice')),
                ('po_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='purchasing.purchaseorderline')),
            ],
        ),
    ]
