# Generated by Django 6.0.4 on 2026-05-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_businesspartneraddress'),
        ('purchasing', '0004_alter_invoice_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='partners.businesspartner'),
        ),
    ]
