# Generated by Django 6.0.4 on 2026-05-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_alter_invoice_supplier'),
        ('sales', '0004_remove_rfqresponse_rfq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='sales_order',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sales_orders',
            field=models.ManyToManyField(blank=True, related_name='purchase_orders', to='sales.salesorder'),
        ),
    ]
