# Generated by Django 6.0.4 on 2026-05-09 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('desc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Clarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('num_code', models.IntegerField()),
                ('desc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('desc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('desc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_wards', models.CharField(default='xxx', max_length=50)),
                ('code_internal', models.CharField(default='xxx', max_length=50)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='xxx', max_length=4)),
                ('desc', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency', to='inventory.currency')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner', to='partners.businesspartner')),
                ('status', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='inventory.status')),
            ],
        ),
        migrations.CreateModel(
            name='GemDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certification_number', models.CharField(blank=True, max_length=30, null=True)),
                ('carat_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('origin', models.CharField(blank=True, max_length=30, null=True)),
                ('clarity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clarity', to='inventory.clarity')),
                ('color', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color', to='inventory.color')),
                ('cut', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cut', to='inventory.cut')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='inventory.item')),
            ],
        ),
    ]
