# Generated by Django 6.0.4 on 2026-05-18 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('partners', '0002_businesspartneraddress'),
        ('purchasing', '0005_alter_invoice_supplier'),
        ('sales', '0004_remove_rfqresponse_rfq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('opening', 'Opening stock'), ('counted', 'Stock count adjustment'), ('appro_in', 'Received from supplier on appro'), ('appro_out', 'Issued to customer on appro'), ('appro_return_in', 'Returned from customer'), ('appro_return_out', 'Returned to supplier'), ('purchased', 'Purchased from supplier'), ('sold', 'Sold to customer'), ('adjustment', 'Manual adjustment')], max_length=20)),
                ('date', models.DateField()),
                ('parcel_description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('weight_carats', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('price_per_carat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_movements', to='partners.businesspartner')),
                ('customer_memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.salesorder')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='purchasing.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_movements', to='partners.businesspartner')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
