# Generated by Django 6.0.4 on 2026-05-09 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clarity',
            options={'ordering': ['num_code'], 'verbose_name_plural': 'Clarities'},
        ),
        migrations.AlterField(
            model_name='gemdetail',
            name='clarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clarity', to='inventory.clarity'),
        ),
        migrations.AlterField(
            model_name='gemdetail',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='color', to='inventory.color'),
        ),
        migrations.AlterField(
            model_name='gemdetail',
            name='cut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cut', to='inventory.cut'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency', to='inventory.currency'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='inventory.status'),
        ),
    ]
