# Generated by Django 6.0.4 on 2026-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='appro_reference',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
