# Generated by Django 6.0.4 on 2026-05-13 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('rfq_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('raised_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('part_received', 'Part Received'), ('received', 'All Received'), ('closed', 'Closed')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFQ',
                'ordering': ['-raised_date'],
            },
        ),
        migrations.CreateModel(
            name='RFQResponse',
            fields=[
                ('rfqr_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('stone_description', models.TextField(blank=True)),
                ('carat_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('size_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('certificate_type', models.CharField(blank=True, choices=[('GIA', 'GIA'), ('IGI', 'IGI'), ('HRD', 'HRD'), ('AGS', 'AGS')], max_length=10)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_responses_accepted', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sales.rfq')),
                ('supplier', models.ForeignKey(limit_choices_to={'bp_type': 'SUPP'}, on_delete=django.db.models.deletion.PROTECT, related_name='rfq_responses', to='partners.businesspartner')),
            ],
            options={
                'ordering': ['offered_price'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('so_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('raised_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('part_fulfilled', 'Part Fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'bp_type': 'CUST'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='partners.businesspartner')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('sol_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('stone_type', models.CharField(choices=[('diamond', 'Diamond'), ('ruby', 'Ruby'), ('sapphire', 'Sapphire'), ('emerald', 'Emerald'), ('pearl', 'Pearl'), ('other', 'Other')], max_length=20)),
                ('item_type', models.CharField(choices=[('certified', 'Certified Stone'), ('uncertified', 'Uncertified Stone')], default='uncertified', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('rfq_sent', 'RFQ Sent'), ('quoted', 'Quoted'), ('on_order', 'On Order'), ('on_approval', 'On Approval'), ('confirmed', 'Confirmed'), ('returned', 'Returned'), ('returned_to_supplier', 'Returned to Supplier'), ('cancelled', 'Cancelled')], default='requested', max_length=30)),
                ('min_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preferred_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('min_carat', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('preferred_carat', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('max_carat', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('colour_spec', models.CharField(blank=True, max_length=50)),
                ('clarity_spec', models.CharField(blank=True, max_length=50)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('certificate_type', models.CharField(blank=True, choices=[('GIA', 'GIA'), ('IGI', 'IGI'), ('HRD', 'HRD'), ('AGS', 'AGS')], max_length=10)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='inventory.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddField(
            model_name='rfq',
            name='sales_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='sales.salesorderline'),
        ),
        migrations.CreateModel(
            name='ApprovalNote',
            fields=[
                ('approval_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('issued_date', models.DateField()),
                ('approval_days', models.IntegerField(choices=[(14, '14 days'), (28, '28 days')], default=14)),
                ('expiry_date', models.DateField(editable=False)),
                ('certificate_type', models.CharField(blank=True, choices=[('GIA', 'GIA'), ('IGI', 'IGI'), ('HRD', 'HRD'), ('AGS', 'AGS')], max_length=10)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmed'), ('returned', 'Returned'), ('expired', 'Expired')], default='active', max_length=20)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('return_type', models.CharField(blank=True, choices=[('to_stock', 'Return to Stock'), ('to_supplier', 'Return to Supplier')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_notes', to='partners.businesspartner')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_notes_issued', to=settings.AUTH_USER_MODEL)),
                ('sales_order_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval_note', to='sales.salesorderline')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
    ]
