# Generated by Django 6.0.4 on 2026-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
