# Generated by Django 6.0.4 on 2026-05-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_businesspartneraddress'),
        ('sales', '0002_salesorderline_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_po_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='partners.businesspartneraddress'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='required_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
