# Generated by Django 6.0.4 on 2026-05-15 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_businesspartneraddress'),
        ('sales', '0003_salesorder_customer_po_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqresponse',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='rfqresponse',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='rfqresponse',
            name='supplier',
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='so_lines', to='partners.businesspartner'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='supplier_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='RFQ',
        ),
        migrations.DeleteModel(
            name='RFQResponse',
        ),
    ]
