# nginx/default.dev.conf
# Development only - no SSL

server {
    listen 80;
    server_name localhost;

    # WebSockets → Daphne
    location /ws/ {
        proxy_pass             http://emillar_daphne:9000;
        proxy_http_version     1.1;
        proxy_set_header       Upgrade $http_upgrade;
        proxy_set_header       Connection "upgrade";
        proxy_set_header       Host $host;
        proxy_read_timeout     86400;
    }

    # Django API
    location /api/ {
        proxy_pass       http://emillar_backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Django Admin
    location /admin/ {
        proxy_pass       http://emillar_backend:8000;
        proxy_set_header Host $host;
    }

    # Django static files
    location /static/ {
        alias /staticfiles/;
    }

    # Vite dev server
    location / {
        proxy_pass             http://emillar_frontend:5173;
        proxy_set_header       Host $host;
        proxy_http_version     1.1;
        proxy_set_header       Upgrade $http_upgrade;
        proxy_set_header       Connection "upgrade";
    }
}
