# Generated by Django 6.0.4 on 2026-05-09 16:39

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('bp_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bp_type', models.CharField(blank=True, max_length=10, null=True)),
                ('bp_int_ref', models.CharField(blank=True, max_length=10, null=True)),
                ('bp_name', models.CharField(max_length=50)),
                ('bp_desc', models.TextField(blank=True, max_length=250, null=True)),
                ('bp_alias_1', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_alias_2', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_comp_name', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_addr_1', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_addr_2', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_addr_3', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_addr_4', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_city', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_county', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_country', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_pcode', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('bp_tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, null=True, region=None)),
                ('bp_mob', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, null=True, region=None)),
                ('bp_fax', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, null=True, region=None)),
                ('bp_whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('bp_fbook', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
