# Generated by Django 6.0.4 on 2026-05-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartnerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('delivery', 'Delivery'), ('registered', 'Registered')], default='delivery', max_length=20)),
                ('line_1', models.CharField(max_length=100)),
                ('line_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=60)),
                ('county', models.CharField(blank=True, max_length=60)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(default='GB', max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='partners.businesspartner')),
            ],
            options={
                'ordering': ['bp', 'address_type'],
            },
        ),
    ]
